### ISSUE TITLE
Request: Provide Pre Built wheels for bt

### ISSUE THREAD

**Issue by gerrymanoim** [pmorissette/bt#171]
Bt is great! Unfortunately, I've had various problems building bt (because of the cython pieces), especially on newer versions of python/windows without admin access. 

I was able to use [cibuildwheel](https://github.com/joerick/cibuildwheel) and appveyor to get myself windows build wheels automatically using the following config:

```
build_script:
  - set CIBW_SKIP=cp27-* cp33-* cp34-* cp35-*
  - pip install cython
  - pip install cibuildwheel==0.9.4
  - cibuildwheel --output-dir wheelhouse
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
```
I'm happy to prototype the TravisCI builds as well if this is of interest and you would be open to uploading the wheels to PiPY. There seem to be ways to automate that, but I'm not sure exactly what your release process is.
